### PR TITLE
Turn webassembly.github.io into minimal project landing page

### PR DESCRIPTION
**Pull request by s3ththompson**
A few months ago I made some minor updates to the [design/README.md](github.com/WebAssembly/design/README.md) to make it a more suitable as a project overview. Based on feedback from that PR (WebAssembly/design#471) and the continued maturity of the project, I think it makes sense to have a very minimal landing page hosted at [webassembly.github.io](http://webassembly.github.io).

Feedback and comments welcome.

### CODE REVIEW

**Comment by s3ththompson** [comment]
(closes WebAssembly/design#478)

Here's a [preview](https://rawgit.com/s3ththompson/webassembly.github.io/master/index.html) of the static files.

**Comment by jfbastien** [comment]
Could you add a README.md to this repo, explaining how to manually update the content?

Looks great otherwise.

**Comment by s3ththompson** [comment]
@jfbastien done!

**Comment by lukewagner** [comment]
Nice job, this is clean and attractive!  I just noticed that "dynamic linking" should probably be in the "Soon after MVP" column, but this is a "preexisting bug" in the design repo.

**Comment by s3ththompson** [comment]
@lukewagner done. want to submit the move in the design repo?

**Comment by lukewagner** [comment]
Thanks, will do, lgtm!

**Comment by lukewagner** [comment]
Filed [design/#532](https://github.com/WebAssembly/design/pull/532).

**Comment by sunfishcode** [comment]
Overall this lgtm! My one concern is the waterfall link; the content there doesn't seem to be appropriate for being linked to from the landing page for newcomers.

**Comment by s3ththompson** [comment]
@sunfishcode Understood.  It's still the only link which provides a heads-up view of the different components of the WebAssembly project, how they fit together, and what's currently working.  WDYT about leaving it for now, and then working on a more beginner-friendly repo/component overview page? Or moving it elsewhere on this landing page with additional context about what it depicts?

**Comment by sunfishcode** [comment]
@s3ththompson I'm confused; the waterfall page linked to here doesn't give a heads-up view of the different components. It just shows upstream LLVM commits, most of which are not related to WebAssembly at all, and it's very confusing. I'd suggest just removing it until we figure out what makes sense to add. For most newcomers, "what currently works" isn't a very interesting set at the present moment anyway.

**Comment by s3ththompson** [comment]
@sunfishcode Clicking through to the tests run on each commit shows how compilation works with LLVM / Binaryen and execution with d8 or the Binaryen shell. I agree, however, that it's not a beginner-friendly interface yet. Moved to the contributing section (with additional context) until we can make it a more useful heads-up view. Look good now?

**Comment by sunfishcode** [comment]
Looks good, thanks.

**Pull request merged**
