### PR TITLE
Demo web page

### PR DESCRIPTION
**Pull request by s3ththompson**
Staging URL: https://rawgit.com/WebAssembly/webassembly.github.io/stage-demo/demo/ (note: proxy doesn't serve wasm binary with appropriate headers)

- [x] Remove BananaBread demo
- [x] ~~Add asm.js fallback to AngryBots~~ (added link to existing asm.js version instead)
- [x] Add AngryBots screenshot
- [x] Improve instructions
- [x] Flesh out stability table
- [x] Polish design

screen shot 2016-03-15 at 3 05 42 am

### CODE REVIEW

**Comment by s3ththompson** [comment]
Added very rough scaffolding. Content & design still in flux. Currently can choose between AngryBots and BananaBread.

**Comment by s3ththompson** [comment]
Hmm... rawgit.com has an error serving the demos right now. Will debug tomorrow...

**Comment by s3ththompson** [comment]
@jfbastien just following the convention of the existing Unity compat check.

**Comment by s3ththompson** [comment]
@titzer @rossberg-chromium ready to merge, can you take a look? I will add a bit more polish in a followup PR, but I want to push the demo bits live in order to give them time to be cached by the GitHub Pages CDN.

**Comment by titzer** [comment]
lgtm

**Pull request merged**
